
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.19  # helm search repo argo/argo-workflows --versions | head -5
    helm:
      valuesObject:
        workflow:
          serviceAccount:
            create: true
            name: argo-workflows-sa
        server:
          extraArgs:
            - --auth-mode=server
        controller:             # https://stackoverflow.com/questions/64924481/argo-workflow-always-using-default-serviceaccount
          workflowNamespaces:   # which links to: https://github.com/argoproj/argo-helm/blob/bbac4b365b23630d2d2812522be3ee161e9bd269/charts/argo-workflows/values.yaml#L55
            - argo-workflows    # might need to keep adding namespaces where jobs are run
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflows-ingressroute
  namespace: argo-workflows
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argo-workflows.localhost`)
      services:
        - name: argo-workflows-server
          port: 2746

---

